version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '11111:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  database_data:
    driver: local