//Import for back-end web application processing
const express = require('express');
//Import for stripe payment processing
//Replace "secret key" with secret key found in Stripe profile under development tools
const stripe = require('stripe')('sk_test_51JbwzUCFPKuFjBGBHJRGp5CncVpHj2MiqP9bs1qbA5aCQfXdyfreaA1fFNnRgS4aSYSPqMcXcFl0HsMoLSD4RncT00yH7yyKxJ'); 
//Import for pathing
const path = require('path');

const app = express();

app.use(express.urlencoded({extended: false}));				//Set native ExpressJS body parser

app.set('view engine', 'ejs');								//Set view engine to EJS, processes HTML directly
app.engine('html', require('ejs').renderFile);				//Use EJS to render HTML files

app.use(express.static(path.join(__dirname, './views')));	//Denotes current directory of static files

app.post("/charge", (req, res) => {							//Invoke upon submission of form
	try {
		stripe.customers									//Create new customer, also used to create token
			.create({
				name: req.body.name,							//name from form
				email: req.body.email,							//email from form
				source: req.body.stripeToken					//token generated by form
			})
		.then(customer =>
			stripe.charges.create({
				amount: req.body.amount * 100,					//charge user requested monetary amount
				currency: "usd",								//set currency to US dollars
				customer: customer.id							//generate customer ID
			})
		)
		.then(() => res.render("completed.html"))			//Load page for completion
		.catch(err => console.log(err));					//Load error page
	} catch (err) {											//Catch general errors
		res.send(err);
	}
});

const port = process.env.PORT || 3000;						//Run app on port 3000 or first available port
app.listen(port, () => {
	console.log('Server is running on port ' + port + '...');
});
