on:
  push:
    branches:
      - stage
name: Update EC2
jobs:
  update:
    name: Prod - SSH Login, Pull, Reload
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        uses: appleboy/ssh-action@v0.1.4
        with:
          script: |
            cd carsons-village-stage
            git checkout stage
            git pull
            npm install
            npx prisma migrate deploy
            npm run build
            pm2 restart all
          host: pages.carsonsvillage.org
          username: ubuntu
          key: ${{ secrets.CARSONS_AWS_API_PRIVATE_KEY }}
